repos:
    - repo: https://github.com/pycqa/isort
      rev: 6.0.0
      hooks:
          - id: isort
            files: project_hnp

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.7
      hooks:
          - id: ruff
            name: ruff linter
            args: [--fix]
            files: project_hnp
          - id: ruff-format
            name: ruff formatter
            files: project_hnp

    - repo: https://github.com/codespell-project/codespell
      rev: v2.4.1
      hooks:
          - id: codespell
            additional_dependencies: [tomli]
            files: project_hnp

    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0
      hooks:
          - id: pydocstyle
            files: project_hnp
            additional_dependencies: [tomli]

    - repo: https://github.com/pappasam/toml-sort
      rev: v0.24.2
      hooks:
          - id: toml-sort-fix
            files: pyproject.toml

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.35.1
      hooks:
          - id: yamllint
            args: [--strict, -c, .yamllint.yaml]
            files: (.github/|.codecov.yaml|.pre-commit-config.yaml|.yamllint.yaml)
